---
version: "3.9"
services:
  students-srv:
    build:
      context: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - MYSQL_SERVER= students-db
    networks:
      - student-srv-net
      
    depends_on:
      - students-db
  students-db:
    image: mysql:5.6
 
    networks:
      - student-srv-net

    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops

networks:
  student-srv-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"
  student-prv-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.101.0/24"
        
